services:
  mysql:
    image: mysql:8.0
    container_name: mysql-node
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: sa
      MYSQL_PASSWORD: sapassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nodeapp:
    build: ./node-app
    container_name: nodejs-app
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb

volumes:
  mysql_data:

