services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - user-service
      - order-service
    networks:
      - backend

  user-service:
    build:
      context: ./UserService
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - backend

  product-service:
    build:
      context: ./ProductService
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - backend

  order-service:
    build:
      context: ./OrderService
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge